'use strict';var Bx={TAB:0,tg:1,pj:2},Cx=function(a){ib("MediaRouter.CastStreaming.Start.Success",a,Bx)};var Dx=Pa("mr.mirror.cast.LogUploader"),Fx=function(a,b,c){Ex("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},Ex=function(a,b,c,d){if(0==b.size)Dx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Pj("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;Zj(a)?(b=ak(a),Dx.info("Upload to Crash succeeded: "+
b)):Dx.info("Upload to Crash failed. HTTP status: "+a.Ba());d&&d(b)},"POST",e,void 0,3E4)}};var Gx=function(){this.a=0;Lg(this)},Ix=function(){Hx||(Hx=new Gx);return Hx},Jx=function(){var a=Ix(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction};Gx.prototype.ha=function(){return"mirror.cast.LogUtils"};Gx.prototype.xa=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};Gx.prototype.Ca=function(){var a=Jg(this);this.a=a&&a.lastAutoSubmitMillis||0};var Hx=null;Pa("mr.mirror.cast.LogUtils");var Kx=Pa("mr.NetworkUtils"),Lx=function(a,b){return of?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(v(Kx,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Kx.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Mx=function(){this.a=Promise.resolve(1)},Ox=function(a,b,c){return Nx(a,function(a){return a==b},c)},Px=function(a,b){var c=[3,4];return Nx(a,function(a){return-1!=c.indexOf(a)},b)},Qx=function(a,b){a.a=a.a.catch(function(){return 1});return Nx(a,function(){return!0},b)},Nx=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Rx(a);try{var h=c(f)}catch(u){h=
Promise.reject(u)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},Rx=function(a){this.b=a;this.a=null},Sx=function(a,b){a.a="number"===typeof b?b:a.b};var Tx={kq:"OFFER",dn:"ANSWER",Eq:"PRESENTATION",xo:"GET_STATUS",tr:"STATUS_RESPONSE",wo:"GET_CAPABILITIES",zn:"CAPABILITIES_RESPONSE",er:"RPC"};var Ux=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},Xx=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Vx(JSON.parse(a),function(a){b=Wx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Wx=function(a){var b=new Ux;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Yx(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=ja(Object.keys(Tx)),e=d.next();!e.done;e=d.next())if(Tx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(k(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Vx(a.error,function(a){b.error=Zx(a)},function(){throw Error('"error" must be an Object');});Vx(a.answer,function(a){b.a=$x(a)},function(){throw Error('"answer" must be an Object');});Vx(a.status,function(a){b.status=ay(a)},function(){throw Error('"status" must be an Object');
});Vx(a.capabilities,function(a){b.capabilities=by(a)},function(){throw Error('"capabilities" must be an Object');});return b},Vx=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Yx=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},cy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},dy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},ey=function(){this.l=null;this.a=[];this.b=
[];this.f=this.g=this.h=null},$x=function(a){var b=new ey;Yx(a.udpPort,function(a){b.l=a},function(){throw Error('"answer.udpPort" must be a number');});cy(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});cy(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.h=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},fy=function(){this.details=this.description=this.code=null},Zx=function(a){var b=new fy;Yx(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Vx(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},gy=function(){this.b=this.a=null},ay=function(a){var b=new gy;Yx(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});cy(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},hy=function(){this.b=this.a=null},by=function(a){var b=new hy;dy(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;Vx(a,function(a){b=iy(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},jy=function(){this.f=this.m=this.h=this.l=this.v=this.a=this.u=this.b=this.initDataTypes=this.g=null},iy=function(a){var b=new jy;"keySystemName"in a&&(b.g=String(a.keySystemName));dy(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});dy(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});dy(a.secureCodecs,function(a){b.u=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});dy(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});dy(a.videoRobustness,function(a){b.v=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.h=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var ky=function(a){this.j=Pa("mr.mirror.cast.MessageDispatcher");this.g=a;this.a=null;this.b=new Map;this.f=0},ly=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;w(a.j,"Added subscriber for "+b+"-type messages.");a.a||(a.a=Nr(a.g),a.a.onMessage=a.l.bind(a))},my=function(a,b){a.b.delete(b)&&w(a.j,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.va(),a.a=null)};
ky.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var ny=function(a,b,c,d,e){var f=null,h=function(){my(a,c);null!=f&&(clearTimeout(f),f=null)};try{ly(a,c,function(a){e(a)&&h()})}catch(l){e(null,l);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
ky.prototype.l=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Xx(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?v(this.j,b):w(this.j,b);++this.f}};var oy=chrome.cast.streaming,qy=function(a,b,c,d,e){this.Z=a.sessionId;this.v=a.Yd;this.G=a.Zd;this.f=b;this.I=c;this.B=d;this.H=py(e,"onAnswer",this.v);this.K=py(e,"onSessionStop",this.v);this.j=Pa("mr.mirror.cast.StreamingLaunchWorkflow");this.s=new Mx;this.m=this.w=this.u=this.b=this.a=this.h=this.l=this.g=null};
qy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof ry,f=b instanceof ry;(e&&b&&!f||f&&a&&!e)&&Ib("Mixing remoting and non-remoting tracks");return Ox(this.s,1,function(e){d.g=a;d.l=b;d.h=c;d.j.info(function(){return"Launching streaming for "+sy(d)+" "+("to a "+d.G+".")});return ty(d).then(d.A.bind(d)).then(function(a){return uy(d,a).then(function(b){d.H();var c=vy(d,b,a);d.a=wy(d,d.a,c);d.b=wy(d,d.b,c);if(!d.a&&!d.b)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.w=!!b.g;d.m=function(a,b){a==d.a?d.h.vc("Audio stream (id="+a+") error: "+b):a==d.b&&d.h.vc("Video stream (id="+a+") error: "+b)};oy.rtpStream.onError.addListener(d.m);return xy(d,b,c)})}).then(function(){d.j.info(function(){return"Launched streaming for "+sy(d)});d.h.xd(d);Sx(e,2);return{Ak:d.a,Gm:d.b}})})};
qy.prototype.stop=function(){var a=this;return Qx(this.s,function(b){if(!a.g&&!a.l)return Sx(b,1),Promise.resolve();a.j.info(function(){return"Stopping streaming for "+sy(a)+"."});a.m&&(oy.rtpStream.onError.removeListener(a.m),a.m=null);if(a.h){var c=a.h.de();a.h=null}else c=Promise.resolve();return c.then(function(){a.a&&(oy.rtpStream.stop(a.a),oy.rtpStream.destroy(a.a),a.a=null);a.b&&(oy.rtpStream.stop(a.b),oy.rtpStream.destroy(a.b),a.b=null);a.u&&(oy.udpTransport.destroy(a.u),a.u=null);a.K();a.j.info(function(){return"Stopped streaming for "+
sy(a)+"."});a.g=null;a.l=null;Sx(b,1)})})};
var yy=function(a,b){var c=JSON.stringify(b);return Promise.all([a.a&&new Promise(function(b){return oy.rtpStream.getRawEvents(a.a,c,b)}),a.b&&new Promise(function(b){return oy.rtpStream.getRawEvents(a.b,c,b)})]).catch(function(b){a.j.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},zy=function(a){return Promise.all([a.a&&new Promise(function(b){return oy.rtpStream.getStats(a.a,b)}),a.b&&
new Promise(function(b){return oy.rtpStream.getStats(a.b,b)})]).catch(function(b){a.j.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],k(a.filter(function(a){return!!a}))))})},sy=function(a){if(a.g&&a.l)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.l)b="video-only ";else return"stopped";return a.g instanceof ry||a.l instanceof ry?b+"remoting":b+"streaming"},ty=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(oy.rtpStream.destroy(c),c=null);e&&!a.l&&(oy.rtpStream.destroy(e),e=null);a.j.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.b=e;a.u=f;b()};a.g instanceof ry||a.l instanceof ry?oy.session.create(null,null,c):oy.session.create(a.g,a.l,c)})};
qy.prototype.A=function(){for(var a=Qu(),b=Qu(),c=[],d=ja([this.a,this.b]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,h=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,r=f?48E3:9E4,u=ja(oy.rtpStream.getSupportedParams(e)),z=u.next();!z.done;z=u.next())z=z.value,z.payload.payloadType=h,z.payload.maxLatency=this.f.maxLatencyMillis,z.payload.minLatency=this.f.minLatencyMillis,z.payload.animatedLatency=this.f.animatedLatencyMillis,z.payload.ssrc=
l,z.payload.clockRate=r,z.payload.aesKey=a,z.payload.aesIvMask=b,f?(z.payload.channels=2,z.payload.maxBitrate=this.f.audioBitrate,z.payload.maxFrameRate=100):(z.payload.minBitrate=this.f.minVideoBitrate,z.payload.maxBitrate=this.f.maxVideoBitrate,z.payload.maxFrameRate=this.f.maxFrameRate),c.push(new Ay(e,z));return c};
var wy=function(a,b,c){b&&!c.some(function(a){return a.nd==b})&&(v(a.j,"Destroying RTP stream not selected by the receiver: id="+b),oy.rtpStream.destroy(b),b=null);return b},uy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,l={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.f.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.f.dscpEnabled&&(l.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.f.maxWidth,height:a.f.maxHeight}]});e.push(l)}var r=a.g instanceof ry||a.l instanceof ry?"remoting":"mirroring",u={type:"OFFER",sessionId:a.Z,seqNum:jk(a.I),offer:{castMode:r,receiverGetStatus:!0,supportedStreams:e}};a.j.info(function(){return"Sending OFFER message: "+JSON.stringify(u)});ny(a.B,u,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=u.seqNum)return v(a.j,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=r||!e&&"mirroring"!=r)&&a.j.error("Expected receiver to ANSWER with castMode="+r+", but got: "+e);w(a.j,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},vy=function(a,b,c){if(b.a.length!=b.b.length)return a.j.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var h=b.a[f];if(0>h||h>=
c.length)return a.j.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.nd==a.candidate.nd}}(e)))return a.j.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.j.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},xy=function(a,b,c){var d=null,e=function(){d&&(oy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.l||2344;a.j.info(function(){return"Starting RTP streams to receiver at "+(a.v+":"+f)+(" for selected offers: "+JSON.stringify(c))});var r=a.u||-1;a.f.dscpEnabled&&(a.j.info("Enabled DSCP in sender."),oy.udpTransport.setOptions(r,{DSCP:!0}));oy.udpTransport.setDestination(r,{address:a.v,port:f});var u=new Set(c.map(function(a){return a.nd}));
d=function(a){u.delete(a);0==u.size&&e()};oy.rtpStream.onStarted.addListener(d);r=ja(c);for(var z=r.next();!z.done;z=r.next())z=z.value,oy.rtpStream.toggleLogging(z.nd,a.f.enableLogging),oy.rtpStream.start(z.nd,z.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},py=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.j.error("Error from testHooks."+b,e)}}:function(){}},Ay=function(a,b){this.nd=
a;this.params=b},ry=function(){};var Dy=function(a,b,c,d,e,f){this.h=a;this.A=By(b,this.h.tb);this.w=new qy(this.h.tb,c,d,e,f);this.v=e;this.g=new Mx;this.b=new Cy;this.u=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.j=Pa("mr.mirror.cast.MediaRemoter");this.m=this.a=this.l=this.f=this.s=null};
Dy.prototype.Ha=function(a,b){var c=this;return Ox(this.g,1,function(d){c.s=a;c.f=b;var e=c.u.createInterfacePtrAndBind();c.u.setConnectionErrorHandler(function(){c.j.info("Remoter mojo pipe connection error.");Ey(c)});c.a=new mojo.MirrorServiceRemotingSourcePtr;var f=Mf(c.h.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.h.mediaSource);c.j.info("Connecting remoter to browser: tabId="+f);(Pf.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.a));
c.a.ptr.setConnectionErrorHandler(function(){c.j.info("RemotingSource mojo pipe connection error.");Ey(c)});c.a.onSinkAvailable(c.A);Sx(d,2);return Promise.resolve()})};var Ey=function(a){return Qx(a.g,function(b){a.a&&(a.a.ptr.reset(),a.a=null);var c=a.l;a.l=null;a.f=null;a.s=null;a.u.close();return new Promise(function(d){window.setTimeout(function(){Fy(a).then(function(){Sx(b,1);d();c&&c()})},250)})})};Dy.prototype.nm=function(a){Gy(this.b,a)};Dy.prototype.sendMessageToSink=Dy.prototype.nm;
Dy.prototype.xd=function(a){this.f&&this.f.xd(a)};Dy.prototype.de=function(){return this.f?this.f.de():Promise.resolve()};Dy.prototype.vc=function(a,b){this.j.error("Error during streaming: "+a,b);if(this.a)this.a.onError();Ey(this)};
Dy.prototype.start=function(){var a=this,b=!1;this.j.info(function(){b=!0;return"Starting next media remoting session."});b&&Hy(this.b,function(b){return a.j.info(b)});Iy(this.b);Ox(this.g,2,function(b){return(0,a.s)().then(function(c){a.l=c;ly(a.v,"RPC",function(b){if(b.rpc){var c=a.b;b=b.rpc;c.h&&(++c.m,c.b+=b.length,c.h(b))}});Sx(b,3)}).catch(function(c){return Fy(a).then(function(){Sx(b);throw c;})})}).then(function(){a.j.info("Remoting started successfully.")}).catch(function(b){a.j.error("Failed to start remoting",
b);a.a.onError()})};Dy.prototype.start=Dy.prototype.start;
Dy.prototype.xm=function(a,b){var c=this;return Ox(this.g,3,function(d){return c.w.start(a?new ry:null,b?new ry:null,c).then(function(a){Jy(c.b,function(a){return c.v.sendMessage(a)},function(a){c.a.onMessageFromSink(a)});Sx(d,4);return{audio_stream_id:a.Ak||-1,video_stream_id:a.Gm||-1}}).catch(function(a){return Fy(c).then(function(){Sx(d);throw a;})})}).catch(function(a){c.j.error("Failed to start remoting streams",a);Ey(c);return{audio_stream_id:-1,video_stream_id:-1}})};
Dy.prototype.startDataStreams=Dy.prototype.xm;Dy.prototype.stop=function(a){var b=this;Px(this.g,function(c){b.a.onStopped(a);return Fy(b).then(function(){b.j.info("Remoting stopped.");Sx(c,5);(0,b.l)().then(function(){return Ox(b.g,5,function(a){if(b.a)b.a.onSinkAvailable(b.A);Sx(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.j.error("Failed to stop remoting: ",a);Ey(b)})};Dy.prototype.stop=Dy.prototype.stop;
Dy.prototype.Kk=function(){null===this.m&&(this.m=de(this.h.tb.Yd).then(function(a){return a.b||!1}));return this.m.then(function(a){return{rate:(a?1E7:2E6)/8}})};Dy.prototype.estimateTransmissionCapacity=Dy.prototype.Kk;
var Fy=function(a){return a.w.stop().then(function(){my(a.v,"RPC");Ky(a.b);Ly(a.b)})},By=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.wm||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,l=d.video_capabilities,r=b.Zd||"";(a.a||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);
break;case "video":l.push(f.CODEC_BASELINE_SET);break;case "4k":l.push(f.SUPPORT_4K);break;case "h264":l.push(f.CODEC_H264);break;case "vp8":l.push(f.CODEC_VP8);break;case "vp9":r.startsWith("Chromecast Ultra")&&l.push(f.CODEC_VP9);break;case "hevc":r.startsWith("Chromecast Ultra")&&l.push(f.CODEC_HEVC);break;default:c.j.info("Unknown mediaCap name: "+a)}});return d},Cy=function(){this.h=this.l=this.a=null;this.v=this.b=this.m=this.f=this.u=0;this.g=null},Iy=function(a){a.a=[];My(a,performance.now())},
Jy=function(a,b,c){a.l=b;a.h=c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return Gy(a,b.data).then(b.pm,b.ni)})):My(a,performance.now())},Ky=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.ni(b)});a.a=null}a.l=null;a.h=null},Gy=function(a,b){if(a.l){var c=btoa(String.fromCharCode.apply(null,b));++a.u;a.f+=b.length;return a.l({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,pm:c,ni:e})}):Promise.reject(Error("RPC pipe not started"))},
Hy=function(a,b){Ly(a);a.g=setInterval(function(){if(a.a)var c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.v)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.f/d)+" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";My(a,c);c=d}b(c)},3E4)},Ly=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},My=function(a,b){a.u=0;a.f=0;a.m=0;a.b=0;a.v=b};var Ny=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Oy=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Py=function(a,b,c,d,e){this.f=new qy(a,b,c,d,void 0===e?null:e);this.j=Pa("mr.mirror.cast.MediaStreamer");this.l=new Mx;this.g=this.b=this.a=this.h=null};Py.prototype.start=function(a,b){var c=this;return Ox(this.l,1,function(d){c.h=a;c.a=Ny(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=Oy(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return Sx(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,c.g).then(function(){return Sx(d,2)})})};
Py.prototype.stop=function(){var a=this;return Qx(this.l,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.h=null;a.g=null;Sx(b,1)})})};var Qy=function(a){return Ox(a.l,2,function(b){a.j.info("Suspending media streaming...");return a.f.stop().then(function(){a.j.info("Suspended media streaming.");Sx(b,3)})})};
Py.prototype.resume=function(){var a=this;return Ox(this.l,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.j.info("Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){a.j.info("Resumed media streaming.");Sx(b,2)})})};var Ry=function(a,b,c){this.l=a;this.g=b;this.f=c;this.j=Pa("mr.mirror.cast.WifiStatusMonitor");this.a=null;this.b=[]};Ry.prototype.start=function(){var a=this;null==this.a&&(w(this.j,"Starting Wifi Status Monitoring."),this.b=[],ly(this.f,"STATUS_RESPONSE",function(b){return Sy(a,b)}),this.a=setInterval(function(){return Ty(a)},12E4),Ty(this))};Ry.prototype.stop=function(){null!=this.a&&(w(this.j,"Stopping Wifi Status Monitoring."),clearInterval(this.a),this.a=null,my(this.f,"STATUS_RESPONSE"))};
var Sy=function(a,b){if(null!=a.a)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?v(a.j,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.b.length&&a.b.shift(),a.b.push(c),a.j.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else v(a.j,function(){return"Ignoring response without status: "+JSON.stringify(b)})},Ty=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.l,seqNum:jk(a.g),get_status:["wifiSnr","wifiSpeed"]})};var Uy=function(a,b,c,d){this.B=b.Yd;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:lg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Zd};this.A=c;this.w=d;this.g=this.b=this.u=this.h=this.l=this.v=this.f=null;this.a=[]};Uy.prototype.xd=function(a){null!=this.b&&clearInterval(this.b);this.f=a;this.v=Date.now();this.b=setInterval(this.s.bind(this,a),9E5)};
Uy.prototype.de=function(){null!=this.b&&(clearInterval(this.b),this.b=null);if(null!=this.f){var a=this.s(this.f);this.f=null;return a}return Promise.resolve()};Uy.prototype.vc=function(a,b){null==this.l&&(this.l=Date.now(),"function"===typeof a?this.h=a():"string"===typeof a&&(this.h=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var Wy=function(a,b){return(null==a.f?Promise.resolve():a.s(a.f)).then(function(){var c=b.map(function(b){b=Vy(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.ld}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),ld:new Blob(d,{type:"application/json"})}});a.a=[];return c})};
Uy.prototype.s=function(a){var b=this;if(null!=this.g)return this.g;var c=de(this.B).then(function(c){c={receiverVersion:c.a,receiverConnected:c.g,receiverOnEthernet:c.b,receiverHasUpdatePending:c.f,receiverUptimeSeconds:c.l};Object.assign(c,b.m);var d=Date.now();Object.assign(c,{startTime:b.v,endTime:d,activity:sy(a),receiverWifiStatus:Array.from(b.w.b)});b.v=d;null!=b.l&&(Object.assign(c,{streamingErrorTime:b.l,streamingErrorMessage:b.h,streamingErrorCause:b.u}),b.l=null,b.h=null,b.u=null);return c});
return(this.g=Promise.all([c.then(function(b){return yy(a,b)}),c,zy(a)]).then(function(a){var c=ja(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.a.push({events:a,ld:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.a=Vy(b,b.A);b.g=null}))||Promise.resolve()};
var Vy=function(a,b){b-=2;for(var c=[],d=a.a.length-1;0<=d;--d){b-=a.a[d].ld.size+1;if(0>b)break;c.push({events:null,ld:a.a[d].ld});if(null!=a.a[d].events){var e=a.a[d].events.size;b>=e&&(c[c.length-1].events=a.a[d].events,b-=e)}}return c.reverse()};var Xy=function(a,b,c,d){d=void 0===d?null:d;ig.call(this,b);var e=b.tb;this.v=e.sessionId;this.I=e.Yd;this.A=a;this.Z=d;this.j=Pa("mr.mirror.cast.Session");this.u=new Mx;this.m=new ik("mirror.cast.SeqNumGenerator");this.h=new ky(b.id);this.l=new Py(e,this.A,this.m,this.h,this.Z);this.g=null;this.a=new Uy(a,e,c,new Ry(this.v,this.m,this.h));this.f=!1;this.s=null};qa(Xy,ig);g=Xy.prototype;
g.start=function(a){var b=this;return Ox(this.u,1,function(c){var d=new Ya("MediaRouter.CastStreaming.Session.Launch");return Yy(b).then(function(c){b.f=c;return b.l.start(a,b)}).then(function(){if(b.l.f.w){var a=b.a;a.m.tdlsIsOn=b.f;a.w.start();Zy(b)}else b.a.m.tdlsIsOn=b.f;d.a();b.s=new db("MediaRouter.CastStreaming.Session.Length");Sx(c,2);return b})})};
g.stop=function(){var a=this;return Qx(this.u,function(b){a.s&&(a.s.a(),a.s=null);a.a.w.stop();return a.l.stop().then(function(){return a.g?Ey(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?$y(a):Promise.resolve()}).then(function(){a.f=!1;Sx(b,4)})})};
g.mi=function(){var a={sessionId:this.v,seqNum:jk(this.m),type:"PRESENTATION",icons:[]};this.B&&(a.title=this.B);this.iconUrl&&!this.w&&a.icons.push({url:this.iconUrl});this.j.info("Sending session metadata update to receiver: "+this.v);this.h.sendMessage(a)};g.xd=function(a){this.a.xd(a)};g.de=function(){return this.a.de()};g.vc=function(a,b){this.a.vc(a,b);this.j.error(a,b);this.stop()};
var az=function(a,b){return Wy(a.a,b)},Yy=function(a){return a.A.useTdls?Lx(a.I,!0).then(function(b){if("Connected"==b)return a.j.info("Successfully enabled TDLS."),!0;v(a.j,"Did not enable TDLS: result="+b);return!1}).catch(function(b){v(a.j,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},$y=function(a){return Lx(a.I,!1).catch(function(b){return a.j.error("Error while turning TDLS back off",b)})},Zy=function(a){bz(a).then(function(b){(b.a||[]).includes("video")?cz(a,b):v(a.j,
function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){v(a.j,"None/Invalid capabilites response. Media Remoting disabled.",b)})},bz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.v,seqNum:jk(a.m)};a.j.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});ny(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.b!=d.seqNum)return a.j.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;w(a.j,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},cz=function(a,b){Ox(a.u,2,function(c){var d=a.b.tb.Zd||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return v(a.j,"HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
Sx(c),Promise.resolve();a.g=new Dy(a.b,b,a.A,a.m,a.h,a.Z);return a.g.Ha(a.G.bind(a),a).catch(function(b){a.j.error("Media Remoting start failed: "+b.message,b)}).then(function(){return Sx(c)})})};Xy.prototype.G=function(){var a=this;return Ox(this.u,2,function(b){return new Promise(function(c,d){Qy(a.l).then(function(){Sx(b,3);c(a.H.bind(a))}).catch(function(b){a.vc("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Xy.prototype.H=function(){var a=this;return Ox(this.u,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){Sx(b,2);c()}).catch(function(b){a.vc("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var dz=function(){Zf.call(this,"cast_streaming")};qa(dz,Zf);g=dz.prototype;g.getName=function(){return"cast_streaming"};g.ve=function(a,b){return new Xy(a,b,Math.max(20969472,9351424),null)};g.Xe=function(){Cx(0)};g.Ue=function(){Cx(1)};g.Yf=function(){Cx(2)};g.Ve=function(){hb("MediaRouter.CastStreaming.Session.End")};g.We=function(a){ib("MediaRouter.CastStreaming.Start.Failure",a,uf)};g.Td=function(){hb("MediaRouter.CastStreaming.Stream.End")};
g.mf=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&Jx(),e=[9351424];d&&e.push(20969472);return az(a,e).then(function(a){var e=a[a.length-1];a=Ug(a[0].events).catch(function(a){b.F.error("Failed to persist events Blob.",a)});d&&0<e.events.size?Fx(e.events,void 0,b.hl.bind(b)):c&&Ex("stats.json",e.ld,void 0,void 0);return a})})};g.hl=function(a){a&&(Ix().a=Date.now())};
g.Kf=function(a){this.F.info("Received message to upload logs for "+a);return this.a?az(this.a,[20969472]).then(function(b){b=ja(b).next().value;return 0==b.events.size?"":Fx(b.events,a)}):Promise.resolve(ez(this,a))};
var ez=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Ug(new Blob),a.F.info("Uploading saved logs for feedback."),Fx(c,b)},fz=new dz;Yf("mr.mirror.cast.Service",fz);
