'use strict';var ay={TAB:0,Ni:1,Zl:2},by=function(a){Eb("MediaRouter.CastStreaming.Start.Success",a,ay)};var cy=kb("mr.mirror.cast.LogUploader"),ey=function(a,b,c){dy("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},dy=function(a,b,c,d){if(0==b.size)cy.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);rk("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;Bk(a)?(b=Ck(a),cy.info("Upload to Crash succeeded: "+
b)):cy.info("Upload to Crash failed. HTTP status: "+a.Sa());d&&d(b)},"POST",e,void 0,3E4)}};var fy=function(){this.a=0;lh(this)},hy=function(){gy||(gy=new fy);return gy},iy=function(){var a=hy(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction};fy.prototype.ua=function(){return"mirror.cast.LogUtils"};fy.prototype.Pa=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};fy.prototype.Ta=function(){var a=jh(this);this.a=a&&a.lastAutoSubmitMillis||0};var gy=null;kb("mr.mirror.cast.LogUtils");var jy=kb("mr.NetworkUtils"),ky=function(a,b){return Pf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(u(jy,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(jy.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var ly=function(){this.a=Promise.resolve(1)},ny=function(a,b,c){return my(a,function(a){return a==b},c)},oy=function(a,b){var c=[3,4];return my(a,function(a){return-1!=c.indexOf(a)},b)},py=function(a,b){a.a=a.a.catch(function(){return 1});return my(a,function(){return!0},b)},my=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new qy(a);try{var h=c(f)}catch(r){h=
Promise.reject(r)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},qy=function(a){this.b=a;this.a=null},ry=function(a,b){a.a="number"===typeof b?b:a.b};var sy={Xt:"OFFER",Jq:"ANSWER",su:"PRESENTATION",ls:"GET_STATUS",iv:"STATUS_RESPONSE",ks:"GET_CAPABILITIES",cr:"CAPABILITIES_RESPONSE",Su:"RPC"};var ty=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},wy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;uy(JSON.parse(a),function(a){b=vy(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},vy=function(a){var b=new ty;null!=a.sessionId&&(b.sessionId=String(a.sessionId));xy(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=la(Object.keys(sy)),e=d.next();!e.done;e=d.next())if(sy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(l(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}uy(a.error,function(a){b.error=yy(a)},function(){throw Error('"error" must be an Object');});uy(a.answer,function(a){b.a=zy(a)},function(){throw Error('"answer" must be an Object');});uy(a.status,function(a){b.status=Ay(a)},function(){throw Error('"status" must be an Object');
});uy(a.capabilities,function(a){b.capabilities=By(a)},function(){throw Error('"capabilities" must be an Object');});return b},uy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},xy=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Cy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Dy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Ey=function(){this.l=null;this.a=[];this.b=
[];this.f=this.g=this.h=null},zy=function(a){var b=new Ey;xy(a.udpPort,function(a){b.l=a},function(){throw Error('"answer.udpPort" must be a number');});Cy(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Cy(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.h=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},Fy=function(){this.details=this.description=this.code=null},yy=function(a){var b=new Fy;xy(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));uy(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Gy=function(){this.b=this.a=null},Ay=function(a){var b=new Gy;xy(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});Cy(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Hy=function(){this.b=this.a=null},By=function(a){var b=new Hy;Dy(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;uy(a,function(a){b=Iy(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Jy=function(){this.f=this.v=this.h=this.l=this.m=this.a=this.u=this.b=this.initDataTypes=this.g=null},Iy=function(a){var b=new Jy;"keySystemName"in a&&(b.g=String(a.keySystemName));Dy(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Dy(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});Dy(a.secureCodecs,function(a){b.u=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Dy(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Dy(a.videoRobustness,function(a){b.m=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.h=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.v=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var Ky=function(a){this.j=kb("mr.mirror.cast.MessageDispatcher");this.g=a;this.a=null;this.b=new Map;this.f=0},Ly=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;v(a.j,"Added subscriber for "+b+"-type messages.");a.a||(a.a=ss(a.g),a.a.onMessage=a.l.bind(a))},My=function(a,b){a.b.delete(b)&&v(a.j,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.Na(),a.a=null)};
Ky.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Ny=function(a,b,c,d,e){var f=null,h=function(){My(a,c);null!=f&&(clearTimeout(f),f=null)};try{Ly(a,c,function(a){e(a)&&h()})}catch(k){e(null,k);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Ky.prototype.l=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=wy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?u(this.j,b):v(this.j,b);++this.f}};var Oy=chrome.cast.streaming,Qy=function(a,b,c,d,e){this.R=a.sessionId;this.m=a.Nf;this.F=a.ae;this.f=b;this.B=c;this.I=d;this.oa=Py(e,"onAnswer",this.m);this.J=Py(e,"onSessionStop",this.m);this.j=kb("mr.mirror.cast.StreamingLaunchWorkflow");this.s=new ly;this.v=this.w=this.u=this.b=this.a=this.h=this.l=this.g=null};
Qy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Ry,f=b instanceof Ry;(e&&b&&!f||f&&a&&!e)&&ec("Mixing remoting and non-remoting tracks");return ny(this.s,1,function(e){d.g=a;d.l=b;d.h=c;d.j.info(function(){return"Launching streaming for "+Sy(d)+" "+("to a "+d.F+".")});return Ty(d).then(d.A.bind(d)).then(function(a){return Uy(d,a).then(function(b){d.oa();var c=Vy(d,b,a);d.a=Wy(d,d.a,c);d.b=Wy(d,d.b,c);if(!d.a&&!d.b)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.w=!!b.g;d.v=function(a,b){a==d.a?d.h.Qd("Audio stream (id="+a+") error: "+b):a==d.b&&d.h.Qd("Video stream (id="+a+") error: "+b)};Oy.rtpStream.onError.addListener(d.v);return Xy(d,b,c)})}).then(function(){d.j.info(function(){return"Launched streaming for "+Sy(d)});d.h.ff(d);ry(e,2);return{qn:d.a,jq:d.b}})})};
Qy.prototype.stop=function(){var a=this;return py(this.s,function(b){if(!a.g&&!a.l)return ry(b,1),Promise.resolve();a.j.info(function(){return"Stopping streaming for "+Sy(a)+"."});a.v&&(Oy.rtpStream.onError.removeListener(a.v),a.v=null);if(a.h){var c=a.h.Rf();a.h=null}else c=Promise.resolve();return c.then(function(){a.a&&(Oy.rtpStream.stop(a.a),Oy.rtpStream.destroy(a.a),a.a=null);a.b&&(Oy.rtpStream.stop(a.b),Oy.rtpStream.destroy(a.b),a.b=null);a.u&&(Oy.udpTransport.destroy(a.u),a.u=null);a.J();a.j.info(function(){return"Stopped streaming for "+
Sy(a)+"."});a.g=null;a.l=null;ry(b,1)})})};
var Yy=function(a,b){var c=JSON.stringify(b);return Promise.all([a.a&&new Promise(function(b){return Oy.rtpStream.getRawEvents(a.a,c,b)}),a.b&&new Promise(function(b){return Oy.rtpStream.getRawEvents(a.b,c,b)})]).catch(function(b){a.j.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},Zy=function(a){return Promise.all([a.a&&new Promise(function(b){return Oy.rtpStream.getStats(a.a,b)}),a.b&&
new Promise(function(b){return Oy.rtpStream.getStats(a.b,b)})]).catch(function(b){a.j.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],l(a.filter(function(a){return!!a}))))})},Sy=function(a){if(a.g&&a.l)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.l)b="video-only ";else return"stopped";return a.g instanceof Ry||a.l instanceof Ry?b+"remoting":b+"streaming"},Ty=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(Oy.rtpStream.destroy(c),c=null);e&&!a.l&&(Oy.rtpStream.destroy(e),e=null);a.j.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.b=e;a.u=f;b()};a.g instanceof Ry||a.l instanceof Ry?Oy.session.create(null,null,c):Oy.session.create(a.g,a.l,c)})};
Qy.prototype.A=function(){for(var a=pv(),b=pv(),c=[],d=la([this.a,this.b]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,h=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,r=la(Oy.rtpStream.getSupportedParams(e)),y=r.next();!y.done;y=r.next())y=y.value,y.payload.payloadType=h,y.payload.maxLatency=this.f.maxLatencyMillis,y.payload.minLatency=this.f.minLatencyMillis,y.payload.animatedLatency=this.f.animatedLatencyMillis,y.payload.ssrc=
k,y.payload.clockRate=m,y.payload.aesKey=a,y.payload.aesIvMask=b,f?(y.payload.channels=2,y.payload.maxBitrate=this.f.audioBitrate,y.payload.maxFrameRate=100):(y.payload.minBitrate=this.f.minVideoBitrate,y.payload.maxBitrate=this.f.maxVideoBitrate,y.payload.maxFrameRate=this.f.maxFrameRate),c.push(new $y(e,y));return c};
var Wy=function(a,b,c){b&&!c.some(function(a){return a.Pe==b})&&(u(a.j,"Destroying RTP stream not selected by the receiver: id="+b),Oy.rtpStream.destroy(b),b=null);return b},Uy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,k={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.f.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.f.dscpEnabled&&(k.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.f.maxWidth,height:a.f.maxHeight}]});e.push(k)}var m=a.g instanceof Ry||a.l instanceof Ry?"remoting":"mirroring",r={type:"OFFER",sessionId:a.R,seqNum:Lk(a.B),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.j.info(function(){return"Sending OFFER message: "+JSON.stringify(r)});Ny(a.I,r,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=r.seqNum)return u(a.j,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=m||!e&&"mirroring"!=m)&&a.j.error("Expected receiver to ANSWER with castMode="+m+", but got: "+e);v(a.j,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},Vy=function(a,b,c){if(b.a.length!=b.b.length)return a.j.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var h=b.a[f];if(0>h||h>=
c.length)return a.j.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.Pe==a.candidate.Pe}}(e)))return a.j.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.j.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},Xy=function(a,b,c){var d=null,e=function(){d&&(Oy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.l||2344;a.j.info(function(){return"Starting RTP streams to receiver at "+(a.m+":"+f)+(" for selected offers: "+JSON.stringify(c))});var m=a.u||-1;a.f.dscpEnabled&&(a.j.info("Enabled DSCP in sender."),Oy.udpTransport.setOptions(m,{DSCP:!0}));Oy.udpTransport.setDestination(m,{address:a.m,port:f});var r=new Set(c.map(function(a){return a.Pe}));
d=function(a){r.delete(a);0==r.size&&e()};Oy.rtpStream.onStarted.addListener(d);m=la(c);for(var y=m.next();!y.done;y=m.next())y=y.value,Oy.rtpStream.toggleLogging(y.Pe,a.f.enableLogging),Oy.rtpStream.start(y.Pe,y.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},Py=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.j.error("Error from testHooks."+b,e)}}:function(){}},$y=function(a,b){this.Pe=
a;this.params=b},Ry=function(){};var cz=function(a,b,c,d,e,f){this.v=a;this.I=az(b,this.v.Zb);this.B=new Qy(this.v.Zb,c,d,e,f);this.w=e;this.l=new ly;this.f=new bz;this.s=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.j=kb("mr.mirror.cast.MediaRemoter");this.m=this.a=this.h=this.g=this.A=null;this.b=!0;this.u=this.R.bind(this)};
cz.prototype.Ya=function(a,b){var c=this;return ny(this.l,1,function(d){c.A=a;c.g=b;var e=c.s.createInterfacePtrAndBind();c.s.setConnectionErrorHandler(function(){c.j.info("Remoter mojo pipe connection error.");dz(c)});c.a=new mojo.MirrorServiceRemotingSourcePtr;var f=mg(c.v.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.v.mediaSource);c.j.info("Connecting remoter to browser: tabId="+f);(qg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.a));
c.a.ptr.setConnectionErrorHandler(function(){c.j.info("RemotingSource mojo pipe connection error.");dz(c)});return ez(c).then(function(){if(c.b)c.a.onSinkAvailable(c.I);ry(d,2)})})};
var dz=function(a){return py(a.l,function(b){a.a&&(a.a.ptr.reset(),a.a=null);var c=a.h;a.h=null;a.g=null;a.A=null;a.s.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){fz(a).then(function(){ry(b,1);d();c&&c()})},250)})})};cz.prototype.Hp=function(a){gz(this.f,a)};cz.prototype.sendMessageToSink=cz.prototype.Hp;cz.prototype.ff=function(a){this.g&&this.g.ff(a)};
cz.prototype.Rf=function(){return this.g?this.g.Rf():Promise.resolve()};cz.prototype.Qd=function(a,b){this.j.error("Error during streaming: "+a,b);if(this.a)this.a.onError();dz(this)};
cz.prototype.start=function(){var a=this,b=!1;this.j.info(function(){b=!0;return"Starting next media remoting session."});b&&hz(this.f,function(b){return a.j.info(b)});iz(this.f);ny(this.l,2,function(b){return(0,a.A)().then(function(c){a.h=c;Ly(a.w,"RPC",function(b){if(b.rpc){var c=a.f;b=b.rpc;c.h&&(++c.v,c.b+=b.length,c.h(b))}});ry(b,3)}).catch(function(c){return fz(a).then(function(){ry(b);throw c;})})}).then(function(){a.j.info("Remoting started successfully.")}).catch(function(b){a.j.error("Failed to start remoting",
b);a.a.onError()})};cz.prototype.start=cz.prototype.start;
cz.prototype.Yp=function(a,b){var c=this;return ny(this.l,3,function(d){return c.B.start(a?new Ry:null,b?new Ry:null,c).then(function(a){jz(c.f,function(a){return c.w.sendMessage(a)},function(a){c.a.onMessageFromSink(a)});ry(d,4);return{audio_stream_id:a.qn||-1,video_stream_id:a.jq||-1}}).catch(function(a){return fz(c).then(function(){ry(d);throw a;})})}).catch(function(a){c.j.error("Failed to start remoting streams",a);dz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
cz.prototype.startDataStreams=cz.prototype.Yp;cz.prototype.stop=function(a){var b=this;oy(this.l,function(c){b.a.onStopped(a);return fz(b).then(function(){b.j.info("Remoting stopped.");ry(c,5);(0,b.h)().then(function(){return ny(b.l,5,function(a){if(b.a&&b.b)b.a.onSinkAvailable(b.I);ry(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.h=null})}).catch(function(a){b.j.error("Failed to stop remoting: ",a);dz(b)})};cz.prototype.stop=cz.prototype.stop;
cz.prototype.Jn=function(){null===this.m&&(this.m=Ce(this.v.Zb.Nf).then(function(a){return a.b||!1}));return this.m.then(function(a){return{rate:(a?1E7:5E6)/8}})};cz.prototype.estimateTransmissionCapacity=cz.prototype.Jn;
var fz=function(a){return a.B.stop().then(function(){My(a.w,"RPC");kz(a.f);lz(a.f)})},ez=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.j.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.j.error("Pref value not a boolean: "+JSON.stringify(c)):(a.b=!!c.value,a.j.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.b));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
cz.prototype.R=function(a){if(this.a){a=la(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.j.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.b==a)break;this.b=a;this.j.info("mediaRemotingEnabled_ changed to: "+this.b);if(this.b)this.a.onSinkAvailable(this.I);else this.a.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var az=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Xp||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,k=d.video_capabilities,m=b.ae||"";(a.a||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.j.info("Unknown mediaCap name: "+a)}});b.ae&&"Chromecast Ultra"==b.ae&&k.push(f.SUPPORT_4K);return d},bz=function(){this.h=this.l=this.a=null;this.m=this.b=this.v=this.f=this.u=0;this.g=null},iz=function(a){a.a=[];mz(a,performance.now())},jz=function(a,b,c){a.l=b;a.h=
c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return gz(a,b.data).then(b.Jp,b.Xk)})):mz(a,performance.now())},kz=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.Xk(b)});a.a=null}a.l=null;a.h=null},gz=function(a,b){if(a.l){var c=btoa(String.fromCharCode.apply(null,b));++a.u;a.f+=b.length;return a.l({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,Jp:c,Xk:e})}):Promise.reject(Error("RPC pipe not started"))},hz=function(a,
b){lz(a);a.g=setInterval(function(){if(a.a)var c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.m)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.f/d)+" bytes/sec) and ")+("received "+a.v+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";mz(a,c);c=d}b(c)},3E4)},lz=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},mz=function(a,b){a.u=0;a.f=0;a.v=0;a.b=0;a.m=b};var nz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},oz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var pz=function(a,b,c,d,e){this.f=new Qy(a,b,c,d,void 0===e?null:e);this.j=kb("mr.mirror.cast.MediaStreamer");this.l=new ly;this.g=this.b=this.a=this.h=null};pz.prototype.start=function(a,b){var c=this;return ny(this.l,1,function(d){c.h=a;c.a=nz(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=oz(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return ry(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,c.g).then(function(){return ry(d,2)})})};
pz.prototype.stop=function(){var a=this;return py(this.l,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.h=null;a.g=null;ry(b,1)})})};var qz=function(a){return ny(a.l,2,function(b){a.j.info("Suspending media streaming...");return a.f.stop().then(function(){a.j.info("Suspended media streaming.");ry(b,3)})})};
pz.prototype.resume=function(){var a=this;return ny(this.l,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.j.info("Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){a.j.info("Resumed media streaming.");ry(b,2)})})};var rz=function(a,b,c){this.l=a;this.g=b;this.f=c;this.j=kb("mr.mirror.cast.WifiStatusMonitor");this.a=null;this.b=[]};rz.prototype.start=function(){var a=this;null==this.a&&(v(this.j,"Starting Wifi Status Monitoring."),this.b=[],Ly(this.f,"STATUS_RESPONSE",function(b){return sz(a,b)}),this.a=setInterval(function(){return tz(a)},12E4),tz(this))};rz.prototype.stop=function(){null!=this.a&&(v(this.j,"Stopping Wifi Status Monitoring."),clearInterval(this.a),this.a=null,My(this.f,"STATUS_RESPONSE"))};
var sz=function(a,b){if(null!=a.a)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?u(a.j,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.b.length&&a.b.shift(),a.b.push(c),a.j.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else u(a.j,function(){return"Ignoring response without status: "+JSON.stringify(b)})},tz=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.l,seqNum:Lk(a.g),get_status:["wifiSnr","wifiSpeed"]})};var uz=function(a,b,c,d){this.I=b.Nf;this.v={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Ng(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.ae};this.A=c;this.w=d;this.g=this.b=this.u=this.h=this.l=this.m=this.f=null;this.a=[]};uz.prototype.ff=function(a){null!=this.b&&clearInterval(this.b);this.f=a;this.m=Date.now();this.b=setInterval(this.s.bind(this,a),9E5)};
uz.prototype.Rf=function(){null!=this.b&&(clearInterval(this.b),this.b=null);if(null!=this.f){var a=this.s(this.f);this.f=null;return a}return Promise.resolve()};uz.prototype.Qd=function(a,b){null==this.l&&(this.l=Date.now(),"function"===typeof a?this.h=a():"string"===typeof a&&(this.h=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var wz=function(a,b){return(null==a.f?Promise.resolve():a.s(a.f)).then(function(){var c=b.map(function(b){b=vz(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Oe}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Oe:new Blob(d,{type:"application/json"})}});a.a=[];return c})};
uz.prototype.s=function(a){var b=this;if(null!=this.g)return this.g;var c=Ce(this.I).then(function(c){c={receiverVersion:c.a,receiverConnected:c.g,receiverOnEthernet:c.b,receiverHasUpdatePending:c.f,receiverUptimeSeconds:c.l};Object.assign(c,b.v);var d=Date.now();Object.assign(c,{startTime:b.m,endTime:d,activity:Sy(a),receiverWifiStatus:Array.from(b.w.b)});b.m=d;null!=b.l&&(Object.assign(c,{streamingErrorTime:b.l,streamingErrorMessage:b.h,streamingErrorCause:b.u}),b.l=null,b.h=null,b.u=null);return c});
return(this.g=Promise.all([c.then(function(b){return Yy(a,b)}),c,Zy(a)]).then(function(a){var c=la(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.a.push({events:a,Oe:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.a=vz(b,b.A);b.g=null}))||Promise.resolve()};
var vz=function(a,b){b-=2;for(var c=[],d=a.a.length-1;0<=d;--d){b-=a.a[d].Oe.size+1;if(0>b)break;c.push({events:null,Oe:a.a[d].Oe});if(null!=a.a[d].events){var e=a.a[d].events.size;b>=e&&(c[c.length-1].events=a.a[d].events,b-=e)}}return c.reverse()};var xz=function(a,b,c,d){d=void 0===d?null:d;Kg.call(this,b);var e=b.Zb;this.m=e.sessionId;this.B=e.Nf;this.A=a;this.R=d;this.j=kb("mr.mirror.cast.Session");this.u=new ly;this.v=new Kk("mirror.cast.SeqNumGenerator");this.h=new Ky(b.id);this.l=new pz(e,this.A,this.v,this.h,this.R);this.g=null;this.a=new uz(a,e,c,new rz(this.m,this.v,this.h));this.f=!1;this.s=null};Fa(xz,Kg);g=xz.prototype;
g.start=function(a){var b=this;return ny(this.u,1,function(c){var d=new tb("MediaRouter.CastStreaming.Session.Launch");return yz(b).then(function(c){b.f=c;return b.l.start(a,b)}).then(function(){if(b.l.f.w){var a=b.a;a.v.tdlsIsOn=b.f;a.w.start();zz(b)}else b.a.v.tdlsIsOn=b.f;d.a();b.s=new Ab("MediaRouter.CastStreaming.Session.Length");ry(c,2);return b})})};
g.stop=function(){var a=this;return py(this.u,function(b){a.s&&(a.s.a(),a.s=null);a.a.w.stop();return a.l.stop().then(function(){return a.g?dz(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?Az(a):Promise.resolve()}).then(function(){a.f=!1;ry(b,4)})})};
g.Wk=function(){var a={sessionId:this.m,seqNum:Lk(this.v),type:"PRESENTATION",icons:[]};this.I&&(a.title=this.I);this.iconUrl&&!this.w&&a.icons.push({url:this.iconUrl});this.j.info("Sending session metadata update to receiver: "+this.m);this.h.sendMessage(a)};g.ff=function(a){this.a.ff(a)};g.Rf=function(){return this.a.Rf()};g.Qd=function(a,b){this.a.Qd(a,b);this.j.error(a,b);this.stop()};
var Bz=function(a,b){return wz(a.a,b)},yz=function(a){return a.A.useTdls?ky(a.B,!0).then(function(b){if("Connected"==b)return a.j.info("Successfully enabled TDLS."),!0;u(a.j,"Did not enable TDLS: result="+b);return!1}).catch(function(b){u(a.j,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Az=function(a){return ky(a.B,!1).catch(function(b){return a.j.error("Error while turning TDLS back off",b)})},zz=function(a){Cz(a).then(function(b){(b.a||[]).includes("video")?Dz(a,b):u(a.j,
function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){u(a.j,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Cz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.m,seqNum:Lk(a.v)};a.j.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Ny(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.b!=d.seqNum)return a.j.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;v(a.j,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Dz=function(a,b){ny(a.u,2,function(c){var d=a.b.Zb.ae||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return u(a.j,"HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
ry(c),Promise.resolve();a.g=new cz(a.b,b,a.A,a.v,a.h,a.R);return a.g.Ya(a.F.bind(a),a).catch(function(b){a.j.error("Media Remoting start failed: "+b.message,b)}).then(function(){return ry(c)})})};xz.prototype.F=function(){var a=this;return ny(this.u,2,function(b){return new Promise(function(c,d){qz(a.l).then(function(){ry(b,3);c(a.oa.bind(a))}).catch(function(b){a.Qd("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
xz.prototype.oa=function(){var a=this;return ny(this.u,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){ry(b,2);c()}).catch(function(b){a.Qd("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Ez=function(){Ag.call(this,"cast_streaming")};Fa(Ez,Ag);g=Ez.prototype;g.getName=function(){return"cast_streaming"};g.lg=function(a,b){return new xz(a,b,Math.max(20969472,9351424),null)};g.Vg=function(){by(0)};g.Sg=function(){by(1)};g.pi=function(){by(2)};g.Tg=function(){Db("MediaRouter.CastStreaming.Session.End")};g.Ug=function(a){Eb("MediaRouter.CastStreaming.Start.Failure",a,Vf)};g.Hf=function(){Db("MediaRouter.CastStreaming.Stream.End")};
g.lh=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&iy(),e=[9351424];d&&e.push(20969472);return Bz(a,e).then(function(a){var e=a[a.length-1];a=uh(a[0].events).catch(function(a){b.H.error("Failed to persist events Blob.",a)});d&&0<e.events.size?ey(e.events,void 0,b.wo.bind(b)):c&&dy("stats.json",e.Oe,void 0,void 0);return a})})};g.wo=function(a){a&&(hy().a=Date.now())};
g.Xh=function(a){this.H.info("Received message to upload logs for "+a);return this.a?Bz(this.a,[20969472]).then(function(b){b=la(b).next().value;return 0==b.events.size?"":ey(b.events,a)}):Promise.resolve(Fz(this,a))};
var Fz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return uh(new Blob),a.H.info("Uploading saved logs for feedback."),ey(c,b)},Gz=new Ez;zg("mr.mirror.cast.Service",Gz);
